### ISSUE TITLE
Bitmart - Getting unexpected errors after orders created 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5176]
**Describe the bug**
While testing Bitmart, we noticed that the bot returns a `Unexpected error` after orders are  created. There are also instances that the orders failed to be cancelled resulting to error `Failed to cancel order the order..`

Tested on local connection:
![image](https://user-images.githubusercontent.com/73840223/157394913-e75e148e-0a98-4db5-9423-e25fbc04b4c8.png)

Tested on AWS:
![Screenshot 2022-03-09 153834](https://user-images.githubusercontent.com/73840223/157394983-d5799d50-f02a-4dff-8831-e82dffa9e84e.png)

```
2022-03-09 15:13:50,054 - 26760 - hummingbot.connector.exchange.bitmart.bitmart_api_order_book_data_source - ERROR - Unexpected error.
Traceback (most recent call last):
  File "/home/rapcmia/github/dev/hummingbot/connector/exchange/bitmart/bitmart_api_order_book_data_source.py", line 168, in listen_for_trades
    async for raw_msg in ws.iter_messages():
  File "/home/rapcmia/github/dev/hummingbot/core/web_assistant/ws_assistant.py", line 63, in iter_messages
    response = await self._connection.receive()
  File "/home/rapcmia/github/dev/hummingbot/core/web_assistant/connections/ws_connection.py", line 60, in receive
    response = self._build_resp(msg)
  File "/home/rapcmia/github/dev/hummingbot/core/web_assistant/connections/ws_connection.py", line 120, in _build_resp
    data = msg.json()
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 95, in json
    return loads(self.data)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```

**Steps To Reproduce**
1. Create simple pure market making strategy
2. Start the bot and monitor the log panel

**Release version**
dev-1.2

**Attachments**
[pmm-bitmart.zip](https://github.com/hummingbot/hummingbot/files/8212651/pmm-bitmart.zip)

**Comment by reubenyap** [comment]
Please find additional information here:

I am having similar issues.
Running latest docker image Hummingbot v1.1.0
Discord Reuben (Firo)#0001

I'm getting
``async_request_context_base - API relate limit on spot/v1/order_detail (50 calls per 1s) has almost reached Limits used is 50 in the past 1 seconds``
and
``Could not fetch account updates from BitMart. Check API key and network connection.``
``Error calling https://api-cloud.bitmart.com/spot/v1/order_detail. HTTP status is 400. Message: order not exist (See log file for stack trace dump)

This happens almost immediately when I start the bot and have no idea why it's hitting the API limits. It also actually creates the orders but keeps on getting spammed with this non stop.

```
########################################################
###       Pure market making strategy config         ###
########################################################

template_version: 22
strategy: pure_market_making

# Exchange and token parameters.
exchange: bitmart

# Token trading pair for the exchange, e.g. BTC-USDT
market: FIRO-USDT

# How far away from mid price to place the bid order.
# Spread of 1 = 1% away from mid price at that time.
# Example if mid price is 100 and bid_spread is 1.
# Your bid is placed at 99.
bid_spread: 0.35

# How far away from mid price to place the ask order.
# Spread of 1 = 1% away from mid price at that time.
# Example if mid price is 100 and ask_spread is 1.
# Your bid is placed at 101.
ask_spread: 0.35

# Minimum Spread
# How far away from the mid price to cancel active orders
minimum_spread: -100.0

# Time in seconds before cancelling and placing new orders.
# If the value is 60, the bot cancels active orders and placing new ones after a minute.
order_refresh_time: 120.0

# Time in seconds before replacing existing order with new orders at the same price.
max_order_age: 1800.0

# The spread (from mid price) to defer order refresh process to the next cycle.
# (Enter 1 to indicate 1%), value below 0, e.g. -1, is to disable this feature - not recommended.
order_refresh_tolerance_pct: 0.1

# Size of your bid and ask order.
order_amount: 250.0

# Price band ceiling.
price_ceiling: -1.0

# Price band floor.
price_floor: -1.0

# Whether to alternate between buys and sells (true/false).
ping_pong_enabled: false

# Whether to enable Inventory skew feature (true/false).
inventory_skew_enabled: true

# Target base asset inventory percentage target to be maintained (for Inventory skew feature).
inventory_target_base_pct: 60.0

# The range around the inventory target base percent to maintain, expressed in multiples of total order size (for
# inventory skew feature).
inventory_range_multiplier: 1.0

# Initial price of the base asset. Note: this setting is not affects anything, the price is kept in the database.
inventory_price: 1.0

# Number of levels of orders to place on each side of the order book.
order_levels: 2

# Increase or decrease size of consecutive orders after the first order (if order_levels > 1).
order_level_amount: 50.0

# Order price space between orders (if order_levels > 1).
order_level_spread: 1.5

# How long to wait before placing the next order in case your order gets filled.
filled_order_delay: 60.0

# Whether to stop cancellations of orders on the other side (of the order book),
# when one side is filled (hanging orders feature) (true/false).
hanging_orders_enabled: false

# Spread (from mid price, in percentage) hanging orders will be canceled (Enter 1 to indicate 1%)
hanging_orders_cancel_pct: 10.0

# Whether to enable order optimization mode (true/false).
order_optimization_enabled: false

# The depth in base asset amount to be used for finding top ask (for order optimization mode).
ask_order_optimization_depth: 0.0

# The depth in base asset amount to be used for finding top bid (for order optimization mode).
bid_order_optimization_depth: 0.0

# Whether to enable adding transaction costs to order price calculation (true/false).
add_transaction_costs: false

# The price source (current_market/external_market/custom_api).
price_source: external_market

# The price type (mid_price/last_price/last_own_trade_price/best_bid/best_ask/inventory_cost).
price_type: mid_price

# An external exchange name (for external exchange pricing source).
price_source_exchange: binance

# A trading pair for the external exchange, e.g. BTC-USDT (for external exchange pricing source).
price_source_market: FIRO-USDT

# An external api that returns price (for custom_api pricing source).
price_source_custom_api:

# An interval time in second to update the price from custom api (for custom_api pricing source).
custom_api_update_interval: 10.0

#Take order if they cross order book when external price source is enabled
take_if_crossed: false


# Use user provided orders to directly override the orders placed by order_amount and order_level_parameter
# This is an advanced feature and user is expected to directly edit this field in config file
# Below is an sample input, the format is a dictionary, the key is user-defined order name, the value is a list which includes buy/sell, order spread, and order amount
# order_override:
#   order_1: [buy, 0.5, 100]
#   order_2: [buy, 0.75, 200]
#   order_3: [sell, 0.1, 500]
# Please make sure there is a space between : and [
order_override:

# If the strategy should wait to receive cancellations confirmation before creating new orders during refresh time
should_wait_order_cancel_confirmation: true

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/pure-market-making/#configuration-parameters

```

logs_conf_pure_bitmartfirousdt.log

```
2022-03-15 09:24:52,344 - 1 - hummingbot.connector.exchange.bitmart.bitmart_exchange - NETWORK - Failed to cancel all orders.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 817, in cancel_all
    await safe_gather(*tasks)
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 373, in _api_request
    raise IOError(f"Error calling {url}. HTTP status is {response.status}. "
OSError: Error calling https://api-cloud.bitmart.com/spot/v2/cancel_order. HTTP status is 400. Message: Order does not exist
2022-03-15 09:24:52,347 - 1 - hummingbot.connector.exchange.bitmart.bitmart_exchange - WARNING - Failed to cancel all orders on BitMart. Check API key and network connection.
2022-03-15 09:24:52,349 - 1 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2022-03-15 09:24:52,351 - 1 - hummingbot.core.network_iterator - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2022-03-15 09:24:52,419 - 1 - hummingbot.connector.exchange.bitmart.bitmart_exchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2022-03-15 09:24:52,471 - 1 - hummingbot.connector.exchange.binance.binance_order_book_tracker - INFO - Initialized order book for FIRO-USDT. 1/1 completed.
2022-03-15 09:24:52,582 - 1 - hummingbot.connector.exchange.bitmart.bitmart_api_order_book_data_source - ERROR - Unexpected error.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_api_order_book_data_source.py", line 168, in listen_for_trades
    async for raw_msg in ws.iter_messages():
  File "/home/hummingbot/hummingbot/core/web_assistant/ws_assistant.py", line 63, in iter_messages
    response = await self._connection.receive()
  File "/home/hummingbot/hummingbot/core/web_assistant/connections/ws_connection.py", line 60, in receive
    response = self._build_resp(msg)
  File "/home/hummingbot/hummingbot/core/web_assistant/connections/ws_connection.py", line 120, in _build_resp
    data = msg.json()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 95, in json
    return loads(self.data)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
2022-03-15 09:24:52,584 - 1 - hummingbot.connector.exchange.bitmart.bitmart_order_book_tracker - INFO - Initialized order book for FIRO-USDT. 1/1 completed.
2022-03-15 09:24:52,701 - 1 - hummingbot.connector.exchange.bitmart.bitmart_api_user_stream_data_source - INFO - Authenticating to User Stream...
2022-03-15 09:24:52,702 - 1 - hummingbot.connector.exchange.bitmart.bitmart_api_user_stream_data_source - ERROR - Error occurred when authenticating to user stream.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_api_user_stream_data_source.py", line 75, in _authenticate
    ws_response = await ws.receive()
  File "/home/hummingbot/hummingbot/core/web_assistant/ws_assistant.py", line 70, in receive
    response = await self._connection.receive()
  File "/home/hummingbot/hummingbot/core/web_assistant/connections/ws_connection.py", line 60, in receive
    response = self._build_resp(msg)
  File "/home/hummingbot/hummingbot/core/web_assistant/connections/ws_connection.py", line 120, in _build_resp
    data = msg.json()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 95, in json
    return loads(self.data)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
2022-03-15 09:24:52,702 - 1 - hummingbot.connector.exchange.bitmart.bitmart_api_user_stream_data_source - ERROR - Unexpected error with BitMart WebSocket connection. Retrying after 30 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_api_user_stream_data_source.py", line 126, in listen_for_user_stream
    await self._authenticate(ws)
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_api_user_stream_data_source.py", line 75, in _authenticate
    ws_response = await ws.receive()
  File "/home/hummingbot/hummingbot/core/web_assistant/ws_assistant.py", line 70, in receive
    response = await self._connection.receive()
File "/home/hummingbot/hummingbot/core/web_assistant/connections/ws_connection.py", line 60, in receive
    response = self._build_resp(msg)
  File "/home/hummingbot/hummingbot/core/web_assistant/connections/ws_connection.py", line 120, in _build_resp
    data = msg.json()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 95, in json
    return loads(self.data)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
2022-03-15 09:24:52,703 - 1 - hummingbot.connector.exchange.bitmart.bitmart_api_order_book_data_source - NETWORK - Unexpected error with WebSocket connection.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_api_order_book_data_source.py", line 231, in listen_for_order_book_diffs
    async for raw_msg in ws.iter_messages():
  File "/home/hummingbot/hummingbot/core/web_assistant/ws_assistant.py", line 63, in iter_messages
    response = await self._connection.receive()
  File "/home/hummingbot/hummingbot/core/web_assistant/connections/ws_connection.py", line 60, in receive
    response = self._build_resp(msg)
  File "/home/hummingbot/hummingbot/core/web_assistant/connections/ws_connection.py", line 120, in _build_resp
    data = msg.json()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 95, in json
    return loads(self.data)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
2022-03-15 09:24:52,703 - 1 - hummingbot.connector.exchange.bitmart.bitmart_api_order_book_data_source - WARNING - Unexpected error with WebSocket connection. Retrying in 30 seconds. Check network connection.
2022-03-15 09:24:52,704 - 1 - hummingbot.connector.exchange.binance.binance_api_order_book_data_source - INFO - Subscribed to public order book and trade channels...
2022-03-15 09:24:53,105 - 1 - hummingbot.connector.exchange.bitmart.bitmart_exchange - ERROR - Error calling https://api-cloud.bitmart.com/spot/v1/order_detail. HTTP status is 400. Message: order not exist
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 585, in _status_polling_loop
    await safe_gather(
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 645, in _update_order_status
    raise response
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 373, in _api_request
    raise IOError(f"Error calling {url}. HTTP status is {response.status}. "
OSError: Error calling https://api-cloud.bitmart.com/spot/v1/order_detail. HTTP status is 400. Message: order not exist
2022-03-15 09:24:53,106 - 1 - hummingbot.connector.exchange.bitmart.bitmart_exchange - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 585, in _status_polling_loop
    await safe_gather(
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 645, in _update_order_status
    raise response
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 373, in _api_request
    raise IOError(f"Error calling {url}. HTTP status is {response.status}. "
OSError: Error calling https://api-cloud.bitmart.com/spot/v1/order_detail. HTTP status is 400. Message: order not exist
2022-03-15 09:24:53,106 - 1 - hummingbot.connector.exchange.bitmart.bitmart_exchange - WARNING - Could not fetch account updates from BitMart. Check API key and network connection.
2022-03-15 09:24:53,608 - 1 - hummingbot.core.api_throttler.async_request_context_base - INFO - API rate limit on spot/v1/order_detail (50 calls per 1s) has almost reached. Limits used is 50 in the last 1 seconds
2022-03-15 09:24:54,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (FIRO-USDT) Creating 2 ask orders at (Size, Price): ['5E+2 FIRO, 3.89 USDT', '6E+2 FIRO, 3.94 USDT']
2022-03-15 09:24:54,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (FIRO-USDT) Creating 2 ask orders at (Size, Price): ['5E+2 FIRO, 3.89 USDT', '6E+2 FIRO, 3.94 USDT']
2022-03-15 09:24:54,130 - 1 - hummingbot.connector.exchange.bitmart.bitmart_exchange - INFO - Created LIMIT_MAKER SELL order hummingbot-S-FIRO-USDT-1647336294001838 for 500.00 FIRO-USDT.
2022-03-15 09:24:54,140 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1647336294.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "FIRO-USDT", "amount": "500.00", "price": "3.89", "order_id": "hummingbot-S-FIRO-USDT-1647336294001838", "exchange_order_id": null, "leverage": 1, "position": "NIL", "ev>
2022-03-15 09:24:54,148 - 1 - hummingbot.connector.exchange.bitmart.bitmart_exchange - INFO - Created LIMIT_MAKER SELL order hummingbot-S-FIRO-USDT-1647336294001905 for 600.00 FIRO-USDT.
2022-03-15 09:24:54,155 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1647336294.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "FIRO-USDT", "amount": "600.00", "price": "3.94", "order_id": "hummingbot-S-FIRO-USDT-1647336294001905", "exchange_order_id": null, "leverage": 1, "position": "NIL", "ev>
2022-03-15 09:24:54,264 - 1 - hummingbot.connector.exchange.bitmart.bitmart_exchange - ERROR - Error calling https://api-cloud.bitmart.com/spot/v1/order_detail. HTTP status is 400. Message: order not exist
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 585, in _status_polling_loop
    await safe_gather(
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 645, in _update_order_status
    raise response
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 373, in _api_request
    raise IOError(f"Error calling {url}. HTTP status is {response.status}. "
OSError: Error calling https://api-cloud.bitmart.com/spot/v1/order_detail. HTTP status is 400. Message: order not exist
2022-03-15 09:24:54,264 - 1 - hummingbot.connector.exchange.bitmart.bitmart_exchange - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 585, in _status_polling_loop
    await safe_gather(
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 645, in _update_order_status
    raise response
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 373, in _api_request
    raise IOError(f"Error calling {url}. HTTP status is {response.status}. "
OSError: Error calling https://api-cloud.bitmart.com/spot/v1/order_detail. HTTP status is 400. Message: order not exist
2022-03-15 09:24:54,264 - 1 - hummingbot.connector.exchange.bitmart.bitmart_exchange - WARNING - Could not fetch account updates from BitMart. Check API key and network connection.
2022-03-15 09:24:56,246 - 1 - hummingbot.connector.exchange.bitmart.bitmart_exchange - ERROR - Error calling https://api-cloud.bitmart.com/spot/v1/order_detail. HTTP status is 400. Message: order not exist
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 585, in _status_polling_loop
    await safe_gather(
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 645, in _update_order_status
    raise response
  File "/home/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 373, in _api_request
    raise IOError(f"Error calling {url}. HTTP status is {response.status}. "
OSError: Error calling https://api-cloud.bitmart.com/spot/v1/order_detail. HTTP status is 400. Message: order not exist
```

logs_hummingbot.log

```
2022-03-15 09:24:40,358 - 1 - hummingbot.core.utils.trading_pair_fetcher - ERROR - Connector k2 failed to retrieve its trading pairs. Trading pairs autocompletion won't work.
Traceback (most recent call last):
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/trading_pair_fetcher.py", line 64, in call_fetch_pairs
    self.trading_pairs[exchange_name] = await fetch_fn
  File "/home/hummingbot/hummingbot/connector/exchange/k2/k2_api_order_book_data_source.py", line 62, in fetch_trading_pairs
    async with client.get(f"{constants.REST_URL}{constants.GET_TRADING_PAIRS}", timeout=10) as response:
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 971, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api-q2.fourwordsalluppercase.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)')]
```

**Comment by reubenyap** [comment]
Are there any updates on this?

**Comment by cossoft** [comment]
Hello, any updates?

**Comment by rapcmia** [comment]
Hi @reubenyap, @cossoft this has been reported to Bitmart's maintainer and he will look into it

**Comment by cossoft** [comment]
> Hi @reubenyap, @cossoft this has been reported to Bitmart's maintainer and he will look into it

Hello, 

Whom did you write on Bitmart? I know their technical guys and I can push them to solve this.

BR,
Cosmin

**Comment by reubenyap** [comment]
Hi I'm dealing with Felix Zhi, I think it's an issue on the connector though.

I think it's in relation to the WS public channel address:

New WS subscription address.
Public Channel wss://ws-manager-compress.bitmart.com/api?protocol=1.1
Private Channel wss://ws-manager-compress.bitmart.com/user?protocol=1.1

Note: WS public channel address wss://ws-manager-compress.bitmart.com?protocol=1.1 will be taken down on 2022-02-28 UTC time. The new address is wss://ws-manager-compress.bitmart.com/api?protocol=1.1

**Comment by cossoft** [comment]
> Hi I'm dealing with Felix Zhi, I think it's an issue on the connector though.
> 
> I think it's in relation to the WS public channel address:
> 
> New WS subscription address. Public Channel wss://ws-manager-compress.bitmart.com/api?protocol=1.1 Private Channel wss://ws-manager-compress.bitmart.com/user?protocol=1.1
> 
> Note: WS public channel address wss://ws-manager-compress.bitmart.com?protocol=1.1 will be taken down on 2022-02-28 UTC time. The new address is wss://ws-manager-compress.bitmart.com/api?protocol=1.1

They said you can update the code with this new addresses.

**Comment by reubenyap** [comment]
I believe it's in relation to this

https://developer-pro.bitmart.com/en/spot/#2022-01-20

and I can see the wrong WS URL here:
https://github.com/hummingbot/hummingbot/blob/cec60a50629707b1bae73122ab4bd38339a35a32/hummingbot/connector/exchange/bitmart/bitmart_constants.py#L8

**Comment by cossoft** [comment]
Ok..can you correct it?

**Comment by reubenyap** [comment]
I'm not a coder and am unable to test it unfortunately.

**Comment by rapcmia** [comment]
hi @reubenyap I tried to change the WSS_URL to `wss://ws-manager-compress.bitmart.com/api?protocol=1.1` and start a simple PMM strategy but still getting the unexpected errors on the client. I also informed our CMs about this update for Bitmart to follow up with the maintainer so they can fix it. 

Here's a recording what I did earlier:

https://user-images.githubusercontent.com/73840223/162408404-c0e2eb12-6968-4d0f-a0a0-6def13f89834.mp4

**Comment by lgiulian** [comment]
Hi!
I also tried to change the wss link but now the error is this one:
{"errorMessage":"Invalid channel param","errorCode":"90004","event":"subscribe"}

**Comment by lgiulian** [comment]
Hi!
I also changed the wss link with the new one but now the error is this one:

`2022-04-09 09:20:05,466 - 1215389 - hummingbot.connector.exchange.bitmart.bitmart_api_user_stream_data_source - INFO - Authenticating to User Stream...
2022-04-09 09:20:05,764 - 1215389 - hummingbot.core.web_assistant.connections.ws_connection - INFO - Received message: {"errorMessage":"Server Error","errorCode":"95000","event":"login"}
2022-04-09 09:20:05,764 - 1215389 - hummingbot.connector.exchange.bitmart.bitmart_api_user_stream_data_source - ERROR - WebSocket login errored with message: Server Error
NoneType: None
2022-04-09 09:20:05,765 - 1215389 - hummingbot.connector.exchange.bitmart.bitmart_api_user_stream_data_source - ERROR - Error occurred when authenticating to user stream.
Traceback (most recent call last):
  File "/home/iulian/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_api_user_stream_data_source.py", line 82, in _authenticate
    raise ConnectionError
ConnectionError
2022-04-09 09:20:05,765 - 1215389 - hummingbot.connector.exchange.bitmart.bitmart_api_user_stream_data_source - ERROR - Unexpected error with BitMart WebSocket connection. Retrying after 30 seconds...
`

**Comment by lgiulian** [comment]
And another problem is that the new wss link is returning a not so valid json message. It' using ' instead of "

`{
    'data': [
        {
            'price': '0.000091',
            's_t': 1649398001,
            'side': 'sell',
            'size': '211756',
            'symbol': 'DODGE_USDT'
        },`

**Comment by reubenyap** [comment]
Are there any updates on this?

**Comment by JeremyKono** [comment]
Hi @reubenyap, I will talk with the team. Seems like the maintainer is not responsive with our request. We will update you when the team talks to a new maintainer.

**Comment by Longgo1986** [comment]
@JeremyKono Thank you, we are all looking forward

**Comment by reubenyap** [comment]
Any updates on this ?

**Comment by JeremyKono** [comment]
We're still looking for a maintainer for Bitmart, no updates yet @reubenyap

**Comment by reubenyap** [comment]
Understand a new maintainer has been found has there been any progress?

**Comment by PhatJay76** [comment]
I have the other errors resolved in a PR https://github.com/hummingbot/hummingbot/pull/5347

` File "/Users/phatjay/Development/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_api_order_book_data_source.py", line 173, in listen_for_trades
    messages = ujson.loads(messages)
TypeError: Expected String or Unicode`

When I log messages it is a "valid" JSON object - despite when printing out it uses single quotes.

**Comment by assinnata** [comment]
I am getting also 
`hummingbot.connector.exchange.bitmart.bitmart_api_user_stream_data_source - ERROR - WebSocket login errored with message: Server Error`
I have inspected the code and managed to fix the orderbook endpoint, but still receiving Internal Server Error 95000

**Comment by superlazycoder** [comment]
I have gone through and fixed this issue on my repo fork. https://github.com/hummingbot/hummingbot/pull/5353 if someone can look into this that would be great. Thanks.

**Comment by assinnata** [comment]
> I have gone through and fixed this issue on my repo fork. #5353 if someone can look into this that would be great. Thanks.

I am testing it, I was missing the damned `/user` path in my fix. Thanks for sharing this

**Comment by assinnata** [comment]
> I have gone through and fixed this issue on my repo fork. #5353 if someone can look into this that would be great. Thanks.

it works fine

**Comment by rapcmia** [comment]
The fix for this issue has been applied on the release of Hummingbot version 1.5
