### ISSUE TITLE
Huobi - Failed to start Avellaneda MM strategy: stuck into Calculating volatility… no trades tick

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#5771]
Huobi - Avellaneda Market Making strategy stuck into Calculating volatility… no trades tick. Did not strated to place orders

**Steps To Reproduce**
create/start avellaneda_market_making strategy using Huobi

Actual:
After Bot stuck into `Calculating volatility, estimating order book liquidity ... no trades tick`

Expected:
Bot start placing orders after volatility calculation 

[logs_conf_avellaneda_market_making_1.log](https://github.com/hummingbot/hummingbot/files/9705179/logs_conf_avellaneda_market_making_1.log)
[logs_conf_avellaneda_market_making_2.log](https://github.com/hummingbot/hummingbot/files/9705180/logs_conf_avellaneda_market_making_2.log)
[!Avellaneda huobi.zip](https://github.com/hummingbot/hummingbot/files/9705203/Avellaneda.huobi.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/83953535/193778732-63744c1b-6e02-4cba-acc7-6e4cc75f911a.png)

**Release version**
dev-1.9.0, master 1.8.0

**Comment by nikspz** [comment]
tried different pairs, got same behavior for ETH-USDT, AVAX-USDT, ADA-USDT
also tried to change the config (play with risk_factor, volatility_buffer_size and trading_intensity_buffer size) - got the same behavior (stuck into `no trades tick`)

Matej mentioned that there cloud be a problem with `Huobi not receiving trades data.`

![image](https://user-images.githubusercontent.com/83953535/194478310-5897c83b-5f08-43a3-b954-a57887481787.png)

**Comment by rapcmia** [comment]
Severity: P3
Bounty: 10,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to certified connector Houbi

**Comment by mss7082** [comment]
https://github.com/hummingbot/hummingbot/blob/433df629f3a486a1b6e83bfd8a19493ba20e7e85/hummingbot/strategy/avellaneda_market_making/avellaneda_market_making.pyx#L641

Why is this labelled as P3? Avellaneda strategy isn't functional at all. Not working for Huobi, FTX and even binance_papertrade. This is rendering Avellaneda strategy useless in hummingbot.

**Comment by delavegaOpengl** [comment]
I got the same problem on FTX but working on binance paper trade but only on BTC/USDT pair

**Comment by nikspz** [comment]
Tried to retest using FTX, It takes some time for bot to start trading. (Also should have sufficient balance (Base and Quote))

Some exchanges needs a lot of time to finally calculate volatility (because of no trades happened)

![image](https://user-images.githubusercontent.com/83953535/194781229-38290eec-845b-4cb9-a57e-0c48f6a8505a.png)

Avellaneda works (Bot place orders) for: Binance, ascendex, kucoin, okx

**Comment by keithbaum** [comment]
This is related with TradingIntensity kappa not converging. Would recommend to enlarge trading intensity buffer if after several minutes it still doesn't start trading

**Comment by rapcmia** [comment]
Hi @mss7082 @delavegaOpengl thanks for your comments, please be advised that there is a separate ticket related to Avellaneda no trades tick issue which can be found here on https://github.com/hummingbot/hummingbot/issues/5171, we have tried to check this with other connectors in which we found that Huobi is most not working for the strategy atm.

Hi @keithbaum we have tried to set the buffer for both volatility and trading intensity (300s, 500s and 900s) but got no luck of the strategy creating orders for us which we have tested on different market pairs

**Comment by delavegaOpengl** [comment]
Thank you @rapcmia for the info. We tried to enlarge both buffer size but with no luck.
We tried BTC-USD and BTC-USDT pairs on FTX. The same strategy is working on binance paper trade.

**Comment by delavegaOpengl** [comment]
I can confirm that after sometimes both the pair BTC/USD and BTC/USDT are working on FTX.

**Comment by luky1984** [comment]
I can confirm this is annoying as fuck. Since this midnight i am trying to start the robots, still seeing this message, unable to start them. Incredible shit.

**Comment by MementoRC** [comment]
From the strategy, it seems like a normal mode for the strategy, however, it's unclear how the new connectors are emitting the TradeEvent for the TrailingIndicators to be updated and thus resume calculation

**Comment by SupMap** [comment]
Having the same issue on version 1.9.0 and dev 1.10.0, running on Windows WSL (Ubuntu) and AscendEx / AscendEx-Paper. Tried several pairs (ETH-USDT, ...) always the same result, tried increasing the buffer sizes up to 5000, does not help. 

Logs and configurations attached.
[logs.zip](https://github.com/hummingbot/hummingbot/files/9992111/logs.zip)

**Comment by 0xlaine** [comment]
I'm seeing the same issue on Kraken spot, tried both `LUNA2-USD` and `MATIC-USD` both get stuck in `Calculating volatility, estimating order book liquidity ... no trades tick`. I left the `MATIC-USD` running for 12 hours straight without success - it's simply not starting up.

**Comment by nikspz** [comment]
fix has been deployed to development branch and will be available on the next release version 1.11

![image](https://user-images.githubusercontent.com/83953535/207307141-04197cbd-3661-4d20-bb3d-d41e76d8cb35.png)

**Comment by donewiththedollar** [comment]
<img width="1387" alt="Screenshot 2022-12-24 at 12 17 18 PM" src="https://user-images.githubusercontent.com/89611464/209446165-215a7691-2019-4709-82de-a90fe843259d.png">

Still having same issue, I tried dev branch as well. Same issue.

**Comment by BreakingDusk397** [comment]
> Still having same issue, I tried dev branch as well. Same issue.

@donewiththedollar  
Try setting `volatility_buffer_size` and `trading_intensity_buffer_size` to 20, and waiting a few minutes.

**Comment by 0xlaine** [comment]
Still seeing the issue here on Kraken. Running from the `v1.11.0` tag, locally built docker image.

Config:
![Markup on 2023-01-02 at 12:50:58](https://user-images.githubusercontent.com/94804332/210227554-0b763cd5-59f2-4a64-8974-77cdb06b2a59.png)

Log output:
![Markup on 2023-01-02 at 12:52:15](https://user-images.githubusercontent.com/94804332/210227675-4010cf93-32e8-493f-a46d-0c58ecbb77f3.png)

`volatility_buffer_size` and `trading_intensity_buffer_size` are both set to 20, the strategy has been running for more than 1 hour, and I can see in the market-trades window via Kraken PRO that more than 20 orders has been made in the last hour.

Any advice, or has this in fact not been fixed for all exchange providers?

**Comment by space-agent** [comment]
having same issue as @0xlaine, tried with buffer sizes of 50 and then 5000, both had the same issue with plenty of trades happening on the market. There's nothing in the logs that 0xlaine's screenshot doesn't already tell you. Also on 1.11.0, kucoin. I have no idea how the bounties board system works, but also willing to throw $100 at this.

**Comment by space-agent** [comment]
okay, I've done some testing. This strategy type needs a lot more trades going on than one might assume, and setting buffer sizes extremely low allows the bot to work correctly.

**Comment by donewiththedollar** [comment]
> 

What kind of sizes are we talking about here? I've tried more than a few combinations on different liquid and less liquid assets on different exchanges to no success.

**Comment by space-agent** [comment]
> > 
> 
> What kind of sizes are we talking about here? I've tried more than a few combinations on different liquid and less liquid assets on different exchanges to no success.

the bot will show no trades tick for a while. Just let it run and the buffers will eventually fill. For a low liquid pair I usually do 200 and it takes 3-4 hours. By low liquidity I mean 100 trades per hour maybe.
